server {
	listen 127.0.0.1:80;
	listen [::1]:80;
	server_name localhost;

	root /app/public;
	index index.php;

	location = /websocket/ {
		proxy_pass http://127.0.0.1:15241;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location / {
		try_files $uri $uri/ /index.php$is_args$args;
	}

	location = /index.php {
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME /app/public/index.php;
		fastcgi_param PHP_VALUE "opcache.enable=0";
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_read_timeout 90;
	}

	location ~ \.php$ {
		return 404;
	}

	location ~ /\. {
		deny all;
	}
}
