#!/bin/bash

_zkillboard()
{
	local cur prev
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	if [[ ${COMP_CWORD} = 1 ]] ; then
		COMPREPLY=($(compgen -W "$(zkillboard bashList)" -- "${cur}" ) )
	fi

	if [[ ${COMP_CWORD} = 2 ]] ; then
		COMPREPLY=($(compgen -W "$(zkillboard methods $prev )" -- "${cur}" ) )
	fi
}

complete -F _zkillboard -o "default" zkillboard